version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: hh_data
    ports:
      - 5432:5432
    command: postgres -c listen_addresses='*'
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PWD}
    ports:
      - 8080:80
  metabase:
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=hh_data
      - MB_DB_PORT=5432
      - MB_DB_USER=${MB_PWD}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=db
    volumes:
      - ./metabase:/metabase-data
    ports:
      - 3000:3000
    depends_on:
      - db
